/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileOrdersRouteImport } from './routes/profile/orders'
import { Route as ProfileGeneralRouteImport } from './routes/profile/general'
import { Route as ProfileAddressRouteImport } from './routes/profile/address'
import { ServerRoute as AuthCallbackServerRouteImport } from './routes/auth/callback'

const rootServerRouteImport = createServerRootRoute()

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileGeneralRoute = ProfileGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileAddressRoute = ProfileAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const AuthCallbackServerRoute = AuthCallbackServerRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/general': typeof ProfileGeneralRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/about': typeof AboutIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/general': typeof ProfileGeneralRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/about': typeof AboutIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/general': typeof ProfileGeneralRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/about/': typeof AboutIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/login'
    | '/logout'
    | '/register'
    | '/profile/address'
    | '/profile/general'
    | '/profile/orders'
    | '/profile/settings'
    | '/about'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/login'
    | '/logout'
    | '/register'
    | '/profile/address'
    | '/profile/general'
    | '/profile/orders'
    | '/profile/settings'
    | '/about'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/login'
    | '/logout'
    | '/register'
    | '/profile/address'
    | '/profile/general'
    | '/profile/orders'
    | '/profile/settings'
    | '/about/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/auth/callback': typeof AuthCallbackServerRoute
}
export interface FileServerRoutesByTo {
  '/auth/callback': typeof AuthCallbackServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/auth/callback': typeof AuthCallbackServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/auth/callback'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/auth/callback'
  id: '__root__' | '/auth/callback'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  AuthCallbackServerRoute: typeof AuthCallbackServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/general': {
      id: '/profile/general'
      path: '/general'
      fullPath: '/profile/general'
      preLoaderRoute: typeof ProfileGeneralRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/address': {
      id: '/profile/address'
      path: '/address'
      fullPath: '/profile/address'
      preLoaderRoute: typeof ProfileAddressRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface ProfileRouteRouteChildren {
  ProfileAddressRoute: typeof ProfileAddressRoute
  ProfileGeneralRoute: typeof ProfileGeneralRoute
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileAddressRoute: ProfileAddressRoute,
  ProfileGeneralRoute: ProfileGeneralRoute,
  ProfileOrdersRoute: ProfileOrdersRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  AboutIndexRoute: AboutIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  AuthCallbackServerRoute: AuthCallbackServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
